### PR TITLE
Couple small bug fixes

### PR DESCRIPTION
**Pull request by cozylife**
@alecsammon created a couple bug fixes in his repo to fix the JSON Schema errors in the PHP RAML Parser project we're both a part of. He hasn't had time to create a pull request for the changes, so I've decided to create the pull request.

### CODE REVIEW

**Comment by CozyLife** [comment]
Any idea on when you'll have time to merge this pull request? Is there something I can do to speed it along?

**Comment by alecsammon** [comment]
Might be worth looking here: https://github.com/justinrainbow/json-schema/pull/138

**Comment by alecsammon** [comment]
I've create 2 new pull request for these 2 bugs.

See #152 and #153.

**Comment by bighappyface** [comment]
#152 has been merged. What's next for this PR?

**Comment by alecsammon** [comment]
Once #153 has been merged then this PR can be deleted

**Comment by alecsammon** [comment]
@cozylife - both #152 and #153 have been merged - you can delete this PR

**Comment by cozylife** [comment]
Thank you.

**Pull request closed without merging**
