### PR TITLE
[WIP] refactor FormatConstraint, use factory approach

### PR DESCRIPTION
**Pull request by steffkes**
Based on our discussion at #266 a very quick & dirty shot to show the approach i'd thought of.

### CODE REVIEW

**Comment by steffkes** [comment]
even w/o waiting for the build to end, i'm pretty sure it will fail on at least one version - i've put that together on a system that runs PHP 7. which allows a bit more / newer feature than the 5.3 release we need per our requirements

**Comment by steffkes** [comment]
didn't rerun the tests after the latest change, which explains why it failed entirely -.- my bad, fixed pushed already.

**Comment by narcoticfresh** [comment]
@steffkes sorry for the late checking.. 

yea, that looks feasable.. the only thing is that you create many throw-away instances, don't know if this could have much impact and how GC handles it.. 

maybe make a local `$instanceCache` array where you instanciate (and put them there) the first time, then always call `validate()` if it exists (which then needs an `Interface` for the Validator class) in the instance in the array..

We have call graphs that even call `ObjectConstraint->check()` around 2000 times - `Format` checks more by factors then of course - so small stuff like this quickly sums up.

**Comment by digitalkaoz** [comment]
@narcoticfresh check again with the latest PRs merged...should be much better now

**Comment by bighappyface** [comment]
@steffkes is this PR still in play?

**Comment by steffkes** [comment]
@bighappyface thanks for asking, that's a valid question: i guess not. not actively working on a project anymore that uses json-schema that much. so there's currently not much time to work on this PR - i'm sorry for that.

**Comment by bighappyface** [comment]
@steffkes no worries. Thanks for the update.

**Pull request closed without merging**
