### PR TITLE
[Proposal] new constraints name - for PHP7

### LINKED ISSUE #128: String will likely become a reserved word in PHP 7
Although the whole Scalar Type Hint implementation is up in the air, it's very likely that string will become a reserved word in PHP 7: https://wiki.php.net/rfc/scalar_type_hints#reserve_for_future_use
For this reason it might be worth looking into using a different name for this class:

https://github.com/justinrainbow/json-schema/blob/master/src/JsonSchema/Constraints/String.php

Just a heads-up.

### PR DESCRIPTION
**Pull request by lsv**
All constraints objects are now suffixed with *Constraint so we aint running into reserved words.
Suffixed Constraint to all contraints and not just "String"

Will fix #128

### CODE REVIEW

**Comment by Danack** [comment]
+1

Scalar type hints are now merged into master for 7, and so this needs to be pulled, and tagged so that PHP projects can continue to use Composer on 7.

**Comment by rdlowrey** [comment]
:+1:

**Comment by Rican7** [comment]
:+1:

**Comment by KyraD** [comment]
:+1: x :100:

**Comment by bighappyface** [comment]
How do we go about making progress on this? @justinrainbow hasn't made a commit in 8/24/2014 and there are several PRs open to improve this code dramatically. Simply put, I need this package to progress.

I propose we create a new group, fork this repo over to it, and add the new repo/package to packagist for easy composer swap.

Thoughts on how to move this package forward?

**Comment by salathe** [comment]
+1  

Re: forking... I would give @justinrainbow time to do something here, being the (current) canonical repo.

**Comment by justinrainbow** [comment]
Hey guys, sorry for the slow response.  I'm going to merge this PR now for a release, then go through some of the other PR's with tests later today.

As @bighappyface mentioned, I'm not actively working on this project and rarely have time to go through the many PRs.  If anyone is interested in becoming a collaborator, send me a message.  Or if there is another group that would like to take over ownership I'd be happy to transfer it.  Since this project is important for Composer - maybe they would like to take it over? /cc @Seldaek

**Comment by justinrainbow** [comment]
Version [v1.4.0](https://github.com/justinrainbow/json-schema/releases/tag/1.4.0) has now been released

**Comment by bighappyface** [comment]
@justinrainbow I'll collaborate (sorry, no private messages anymore)

**Comment by rdlowrey** [comment]
Hey thanks, @justinrainbow. I'm sure folks understand what a PITA it can be to merge PRs on a project that's on your personal back-burner. No worries and thanks for taking care of it :)

**Comment by Seldaek** [comment]
@justinrainbow kinda have enough on my plate but I think the json-schema spec is fairly stable (dead?) so shouldn't be too often that you need to maintain things on this front :)

**Comment by philsturgeon** [comment]
@justinrainbow Hey, just here to drop an idea out there. [The PHP League](http://thephpleague.com/) has a few times before taken on packages that others did not have time for. It's not so much a dumping ground, but more of a way to stale code. 

It can also be handy for reducing bus factor, so if the project lead is AWOL or gets flattened then we always have other members to look after things.

I asked around on the League mailing list and @shadowhand has offered to pick this up, as he uses it actively. 

Does this sound like a plan?

**Comment by philsturgeon** [comment]
And by plan I mean: we can transfer it to our org, or fork it and Composer can use the fork.

I'd rather go with transfer though as that sorts out any confusion over which version to use and keeps stars/prs/etc.

**Comment by keradus** [comment]
It is cool to have this merged, but...
This changed public interface (class names), which is a BC break, therefore the release should be new MAJOR, not MINOR...

**Comment by onlinesid** [comment]
I've just started using this library but plan to use it on more projects. I'd be interested to become one of the collaborators.

**Pull request merged**
