### PR TITLE
Update readme and simplify interface

### PR DESCRIPTION
**Pull request by shmax**
Updating the readme examples to reflect recent changes.

@digitalkaoz @bighappyface What do you guys think about the idea of moving checkmode back to constraint? It doesn't really seem to have anything to do with the optimizations, and it would make setting flags a little less awkward in the case that you don't want to otherwise inject any dependencies.

### CODE REVIEW

**Comment by digitalkaoz** [comment]
@shmax as its just a bitmask im ok with it, but we must avoid cloning/creating object at all costs

**Comment by shmax** [comment]
Sounds good, I'll submit a PR soon.

**Comment by shmax** [comment]
I went ahead and made the change in this PR. See what ya think...

**Comment by digitalkaoz** [comment]
Go for it

**Comment by shmax** [comment]
Already did! This PR is ready for review.

**Comment by bighappyface** [comment]
Doesn't this change the interface again? It seems like these changes aren't BC with 4.0.0 and would force 5.0.0.

**Comment by shmax** [comment]
Yes, I suppose it would.

**Comment by shmax** [comment]
@bighappyface Have you given any more thought to this PR? There are a few issues open right now that have to do with the documentation not matching the interface:

https://github.com/justinrainbow/json-schema/issues/321
https://github.com/justinrainbow/json-schema/issues/311

**Comment by bighappyface** [comment]
First, let's rename this PR to be more descriptive.

Second, I would like to get some additional community support for a move to 5.0.0 before I merge and go. I am not against it, but I am not a big fan of unilateral action for packages consumed by many people.

**Comment by shmax** [comment]
Sure, no argument there. However, the community has had 2 weeks to chime in on this, and not a peep, so far. What's the best way to encourage some comment?

**Comment by shmax** [comment]
Not as interested in this now that the flag for coercion has been removed.

**Pull request closed without merging**
