### PR TITLE
Don't use PHP's fmod

### LINKED ISSUE #469: False negatives with real values of multipleOf
I use the `multipleOf` property to limit numbers to two decimal places. For example:

"turnover": {
  "type": "number",
  "multipleOf": 0.01
}

When passed a value of `5000000` it fails the constraint and returns an error.  That number is valid for the constraint so this is a false negative.

### PR DESCRIPTION
**Pull request by PeterMead**
This fixes #469.

### CODE REVIEW

**Comment by PeterMead** [comment]
Well I didn't want to criticise the existing code, but yes that function is a bit of a mess.  That's mostly because it's trying to work around the issues with PHP's fmod but if we're not using that any more we can simplify the function.  I think it's still too complicated for a one liner and if it's used in two places it's better to keep the code in one place.

**Comment by bighappyface** [comment]
Per #469 I think it would be nice to have a test demonstrating the false negative.

**Comment by bighappyface** [comment]
@erayd should I hold out for a test on this one?

**Comment by erayd** [comment]
@bighappyface I'm happy with it as-is. It would be handy to have a test at some point, but I don't think we should be delaying this fix for it, noting the lack of resources.

**Pull request merged**
