### PR TITLE
Revert "Do not override error handler"

### PR DESCRIPTION
**Pull request by bighappyface**
Reverts justinrainbow/json-schema#262

### CODE REVIEW

**Comment by bighappyface** [comment]
@Maks3w should I bump to 2.0.4 or is that something else that is wrong to you?

**Comment by Maks3w** [comment]
IIRC semver said in this case a major version should be released. But knowing how Composer work it's better to be released as minor or patch. 

We could consider this like a bug instead of HTTP support drop so release as 2.0.4

**Comment by dmitry-varennikov-eventbase** [comment]
Can anybody point me to the place where `$context` variable used as we reverted to the original code?

**Comment by dmitry-varennikov-eventbase** [comment]
Also would you mind to use my original proposal to use error control operator `@` to suppress errors for `file_get_contents` instead of redefining error handler?

**Comment by bighappyface** [comment]
@dmitry-varennikov-eventbase how about the Curl retriever?

https://github.com/justinrainbow/json-schema/blob/5c133a3e336c2b35a4233f5da4cc15f083ea128d/src/JsonSchema/Uri/Retrievers/Curl.php

**Comment by dmitry-varennikov-eventbase** [comment]
I didn't find any errors mentioning for [curl-exec](http://php.net/manual/en/function.curl-exec.php). So I'm not sure what your question is.

Also I believe `Curl` and `FileGetContents` retrievers should behave the same and both should NOT override php error handler but just throw `ResourceNotFoundException`

**Comment by Maks3w** [comment]
@dmitry-varennikov-eventbase Error supression with `@` its almost not allowed by any project. One option is allow inject a custom error handler.

public $errorHandlersCallables = ['start' => callable, 'end' => callable]

$this->errorHandlersCallables['start']()
....
$this->errorHandlersCallables['end']()

**Comment by dmitry-varennikov-eventbase** [comment]
@Maks3w don't you think it requires too much code for every caller to retrieve a JSON schema file?

**Comment by Maks3w** [comment]
custom error handlers are optional. By default current behavior (set_error_handler) is used.

IMO let this as is and come back when you have an specific real case.

**Comment by dmitry-varennikov-eventbase** [comment]
@Maks3w 
Here's a [specific real case](https://github.com/justinrainbow/json-schema/pull/262) I described in my original PR and suggested a solution to use error control operator `@` instead of overriding error handler. Your answer was 
> Error supression with @ its almost not allowed by any project.

Is it the only argument NOT to use my suggestion?

**Comment by Maks3w** [comment]
May this could work.

```php
$error = false;
set_error_handler(function ($a, $b, ...) use (&$error) { $error = [$a, $b, ...];}
file_get_contents
restore_error_handler
if ($error) {throw Exception($error['a'], $error['b'])}

**Comment by dmitry-varennikov-eventbase** [comment]
Yeah as long as an exception is thrown outside of the re-defined error handler I'm happy with it

**Comment by dmitry-varennikov-eventbase** [comment]
[Throw `ResourceNotFoundException` outside of re-defined error-handler](https://github.com/justinrainbow/json-schema/pull/273)

**Pull request merged**
