### PR TITLE
remove composer.lock

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by bighappyface** [comment]
What's up with the failing test?

**Comment by keradus** [comment]
it looks like this project fails with lowest php and deps...

**Comment by keradus** [comment]
Min version of PHP seems to be ok.
Min deps version looks messed up: https://travis-ci.org/justinrainbow/json-schema/builds/56147406

**Comment by keradus** [comment]
Remove testing lowest deps from travis, please check what they should be and add it yourself.

Ready to merge.

**Comment by bighappyface** [comment]
May we add the `self-update` and `--prefer-source` back in? It's noisy without them.

https://travis-ci.org/justinrainbow/json-schema/jobs/56150828#L217-L225

**Comment by keradus** [comment]
machines without sudo have newer composer, but here you need sudo :(

**Comment by keradus** [comment]
selfupdate back in there.
composer cache wont work with prefer-source

**Comment by bighappyface** [comment]
+1

**Pull request merged**
