### PR TITLE
Create .gitattributes

### PR DESCRIPTION
**Pull request by gsouf**
git attributes allows to reduce size of dependency, very usefull when you create a phar! More explanations: https://www.reddit.com/r/PHP/comments/2jzp6k/i_dont_need_your_tests_in_my_production

### CODE REVIEW

**Comment by ktomk** [comment]
Why exclude the `README.md ? It wouldn't contain much info for the zip package *but* not having one seem unfriendly to me. Maybe better update it?

**Comment by bighappyface** [comment]
@gsouf I agree with @ktomk and the first line should be `docs`

I'll merge with those updates. Good contribution.

**Comment by gsouf** [comment]
I did put README.md because he only files you need in production are the source files

**Comment by bighappyface** [comment]
+1

**Pull request merged**
