### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by fre5h**

### CODE REVIEW

**Comment by erayd** [comment]
Please change the base branch for this PR to 6.0.0-dev. Otherwise looks good :-).

**Comment by fre5h** [comment]
@erayd done

**Comment by erayd** [comment]
Thanks. Could you please rebase it also? Looks like there are a couple of commits in the history for this PR that don't belong there (pulled from master)

**Comment by fre5h** [comment]
@erayd rebases

**Comment by erayd** [comment]
Perfect - thank you :-).

**Pull request merged**
