### PR TITLE
[BUGFIX] Use unicode matching for patterns

### PR DESCRIPTION
**Pull request by jbaron-gingco**
JSON allows all unicode characters, thus the matching should work when using unicode characters.

### CODE REVIEW

**Comment by bighappyface** [comment]
+1

**Comment by jbaron-gingco** [comment]
If you approve of this, could you merge it and maybe even create a new release? This change is important for the application we're developing, and I'd hate to make a fork or require some git branch.

**Comment by bighappyface** [comment]
@shmax are you good with this?

**Comment by shmax** [comment]
Sure, what's not to like? 👍

**Comment by bighappyface** [comment]
@jbaron-gingco please see https://github.com/justinrainbow/json-schema/releases/tag/4.0.1

**Comment by jbaron-gingco** [comment]
Thank you :-)

**Pull request merged**
