### PR TITLE
Enhancement: Speed up builds as much as possible

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] indents `.travis.yml` consistently (unrelated)
* [x] provides feedback quickly if it has failed, using the `fast_finish` option
* [x] moves update of Composer itself to `before_install` section (unrelated)
* [x] runs `composer install` instead of `composer update` (unrelated)
* [x] checks links on PHP 5.6 only 
* [x] builds docs on PHP 5.6 only

### Before

screen shot 2015-07-12 at 23 25 43

See https://travis-ci.org/justinrainbow/json-schema/builds/70676013.

### After

screen shot 2015-07-13 at 00 09 41

https://travis-ci.org/justinrainbow/json-schema/builds/70680917.

### CODE REVIEW

**Comment by localheinz** [comment]
Seems like most of the time is still spent on installing dependencies with Composer. If links wouldn't needed to be checked on Travis, container-based infrastructure could be enabled, cutting the whole build down to probably around 2 minutes.

**Comment by bighappyface** [comment]
@localheinz would you push the link check and docs build below `phpunit` for the fastest fail on PHP 5.6? We probably should have done that a long time ago considering it's pointless to build the docs for broken code.

Overall I think this is a great improvement.

**Comment by localheinz** [comment]
@bighappyface 

:+1:

**Comment by bighappyface** [comment]
+1

**Pull request merged**
