### PR TITLE
Make the enum element comparison strict

### PR DESCRIPTION
**Pull request by loucho**
The current check is matching numeric strings that are not equal ( like "604.1" == "604.10" because of PHP's == behavior that converts numeric strings to numbers and then performs a numeric comparison), even if type is checked before the comparison, the value should be identic

### CODE REVIEW

**Comment by bighappyface** [comment]
@loucho have you reviewed the failing unit test in the build for this PR?

**Comment by loucho** [comment]
Oh, hadn't thought of that, i just checked it, seems my change fails when comparing an object (I assume that this is because objects are not === unless they are a reference to the same object in memory or something). 

Maybe add a check for objects before making the comparison? what do you think?

**Comment by bighappyface** [comment]
@loucho sorry for the late response. Would you please rebase for a clean build?

**Comment by loucho** [comment]
Rebased and made the change, waiting on the CI tests

**Comment by bighappyface** [comment]
@loucho solid improvement. I am inclined to suggest wrapping the returns in curlies for consistency sake, and a good rebase would distill this PR down to a single new commit, but it's all good.

+1

I will merge this with another :+1: from the community.

Would you mind helping review some other PRs for their community :+1:? I am sure they will return the favor :smile: 

#105 needs review.

**Comment by onlinesid** [comment]
This is a bug fix so +1 !

**Comment by bighappyface** [comment]
Thanks for the review @onlinesid! Let's call this 1.4.1.

**Comment by loucho** [comment]
Sure, will do

**Pull request merged**
