### PR TITLE
chore(LICENSE): switch to MIT

### PR DESCRIPTION
**Pull request by bighappyface**
See #241

### CODE REVIEW

**Comment by rtucek** [comment]
Yeah, like most composer packages, this should be MIT.
Please update the composer.json too!

**Comment by bighappyface** [comment]
@rtucek good catch! Updated.

**Comment by jojo1981** [comment]
@bighappyface I think this one can be merged? Nobody has made any objection...

**Comment by bighappyface** [comment]
@jojo1981 thanks for the review

**Comment by jojo1981** [comment]
Nice, thx!

**Pull request merged**
