### PR TITLE
feat(travis): pivot to container-based infrastructure

### PR DESCRIPTION
**Pull request by bighappyface**
https://docs.travis-ci.com/user/workers/container-based-infrastructure/#Routing-your-build-to-container-based-infrastructure

### CODE REVIEW

**Comment by bighappyface** [comment]
This seems marginally faster than the legacy infrastructure:

Without `sudo:false`: https://travis-ci.org/justinrainbow/json-schema/builds/104474976

> Elapsed time 1 min 58 sec
> Total time 12 min 2 sec

With `sudo:false`: https://travis-ci.org/justinrainbow/json-schema/builds/104475549

> Elapsed time 3 min 34 sec
> Total time 11 min 29 sec

**Comment by bighappyface** [comment]
@localheinz thoughts?

**Comment by localheinz** [comment]
@bighappyface 

Faster is better! :+1:

**Comment by localheinz** [comment]
@bighappyface 

But `sudo` is still needed, isn't it?

See https://github.com/justinrainbow/json-schema/blob/master/.travis.yml#L20.

**Comment by bighappyface** [comment]
@localheinz good question. [I removed the `CHECK_LINKS` environment variable from the PHP 5.6](https://github.com/justinrainbow/json-schema/commit/752c13670ec4ad8f6762bed36ae15122423d9c89) build  to clear up some dependency issues that arose and started breaking the build. You had recommended something along those lines awhile back.

Now that the doc build isn't part of the build process we are good to disable `sudo` and get things up to date.

**Comment by localheinz** [comment]
@bighappyface 

We could speed up the build even further by 

* enabling caching of dependencies installed with composer (see https://github.com/refinery29/league-lazy-event/blob/master/.travis.yml#L20-L23, works best when authenticating with GitHub)
* generating coverage on one build only (see https://github.com/refinery29/league-lazy-event/blob/master/.travis.yml#L15-L16)
* disabling xdebug when we don't need it (see https://github.com/refinery29/league-lazy-event/blob/master/.travis.yml#L27)

In regard to coverage, maybe it makes sense to use https://codeclimate.com? It's free for open source, and it comes with fancy badges for displaying the code quality as well as coverage!

**Comment by bighappyface** [comment]
@localheinz +1

Feel free :)

**Pull request merged**
