### PR TITLE
v6.0.0

### PR DESCRIPTION
**Pull request by bighappyface**
This PR will be used to review the merge of the 6.0.0-dev branch into master.

See https://github.com/justinrainbow/json-schema/projects/2

### CODE REVIEW

**Comment by erayd** [comment]
Sounds good :-).

Do you have an intended timeline around 6.0.0, and would you like a change-freeze for it?

**Comment by erayd** [comment]
(I'm in no particular rush re 6.0.0 - whenever you are ready is fine, and quite happy to keep this open for a while until all the outstanding stuff has been worked through)

**Comment by bighappyface** [comment]
Are you able to edit the 6.0.0 project at all?

https://github.com/justinrainbow/json-schema/projects/2

**Comment by erayd** [comment]
@bigappyface Nope. I can see it, but cannot change anything.

**Comment by erayd** [comment]
It's all good. Sounds like @justinrainbow has been AWOL for years, so there's really not much you can do in that regard without forking. It would be handy, but we can get by without it. We'll be up shit creek if you vanish too though.

What you have listed in the 6.0 0 project looks good, although I would *really* like it if 6.0.0 could also include some kind of document that makes it very clear what is public API, and what is internal to the project, so that we can avoid having to roll a new major version whenever something internal changes.

Can we also have a small change freeze after 6.0.0 looks done, but before it's merged to master, so that there's a bit of time to notice any uncaught bugs that might be problematic to users?

**Comment by bighappyface** [comment]
No problem on the code freeze.

Would you mind opening an issue around the documentation you mentioned? We can talk more about it there and then associate the issue with the 6.0.0 project to keep tabs on progress.

I would also like to get a CONTRIBUTORS document going too. We can put basic expectations and a code review checklist within to help guide folks as they come and go (although it is mostly just us, but people do come and go).

**Comment by erayd** [comment]
@bighappyface #392 :-).

**Comment by bighappyface** [comment]
@erayd I suspected that the backports would cause conflicts. Would you mind opening a PR against `6.0.0-dev` that has changes needed to get that branch out of conflict?

**Comment by erayd** [comment]
Not a problem, hang on.

**Comment by erayd** [comment]
Done in #402. Not as clean as rebasing master on ef3ee8356a2ea9bb44135787dab2f1491dcbb9f7, but workable. Let me know if you want it tweaked.

**Comment by erayd** [comment]
Actually...

**Comment by erayd** [comment]
What do you think of #403?

**Comment by mathroc** [comment]
what about dropping support for [EOL version of php](http://php.net/eol.php) ? by that I mean documenting that only php 5.6+ version are supported so that we can later use features from 5.6+ without having to release a new major version ? At first the lib would still run fine on 5.3

this could be done by marking travis test for those version with `allow_failures` so that support for those versions could still be visible and improved if wanted but wouldn't block new features

**Comment by erayd** [comment]
@mathroc Personally I'd be fine with it, but I don't maintain any legacy systems that *need* an older version, so I'm not sure how common that use-case is. Need to see what others think too I reckon.

**Comment by bighappyface** [comment]
@mathroc @erayd while I am open to dropping support for EOL versions of PHP we are obligated to supporting the same versions as composer being we are a dependency:

https://github.com/composer/composer/blob/eff9326b0de05551e976ca4ddcfc9f057fe29bcb/composer.json#L26

I would like to keep the discussion going but let's move that elsewhere.

**Comment by bighappyface** [comment]
@erayd @shmax how do you feel about things presently for 6.0.0? I am ready to go on next steps.

**Comment by bighappyface** [comment]
^^ pushed the wrong button - please disregard :|

**Comment by shmax** [comment]
LGTM

**Comment by shmax** [comment]
> we are obligated to supporting the same versions as composer being we are a dependency

I don't have a horse in this race either way, but is that really how this is supposed to work? Is there really an inverse dependency and obligation to be aware of other projects that are depending on this one?  I think as long as we obey the rules of semver and bump our major release according to convention we can do what we like without danger of breaking anything, right? Composer seems to cap things off at the next minor branch of 5.0, and we're preparing a 6.0 branch, so I guess I don't see a problem?

**Comment by bighappyface** [comment]
@shmax I agree that the relationship seems weird. See #422 for further discussion on this topic.

**Comment by erayd** [comment]
@bighappyface @shmax @mathroc 

> How do you feel about things presently for 6.0.0? I am ready to go on next steps.

I've listed what I think needs addressing below. What do you consider to be the next steps?

## Outstanding for 6.0.0
 * #401 needs merge.
 * #417 needs fixing.
 * #419 needs merge.
 * #392 needs further discussion, agreement, and some kind of documentation
 * #333 needs fixing.
 * Better overall documentation would be nice to have, but isn't blocking.

## Other Stuff
 * #396 needs further discussion, but could be added in 6.1.0, so not blocking.
 * #395 needs to happen at some point; do we want this in 6.0.0? Boolean schemas are a thing.
 * #391 can be added whenever and is not blocking.
 * #374 is IMO a bug, but should probably be a major-release change. Do we want it in 6.0.0, or should this remain unfixed until 7.0.0? Strict mode will also resolve #29.
 * What's going on with #258?

**Comment by bighappyface** [comment]
@erayd ^^ thanks for the breakdown

**Comment by bighappyface** [comment]
@erayd sorry for the silence. I am completely out of touch on this.

Do we want to look at rolling 6.0.0?

**Comment by bighappyface** [comment]
^^ derp - reading https://github.com/justinrainbow/json-schema/pull/390#issuecomment-301631526 to get familiar again

**Comment by erayd** [comment]
@bighappyface I don't want to roll 6.0.0 yet; I don't think we're ready.There are still a number of outstanding items.

However... I do think that making 6.0.0-dev the default branch (or merging it into master) is a good idea, because that's the primary target for pull requests. The current master branch doesn't really serve any purpose, and isn't the head of any current development.

**Comment by erayd** [comment]
@bighappyface Things would go faster (and be more enjoyable too) if we had significant contribution from others - there currently seems to be a lack of interest to really get things going. Both you and @shmax have been really helpful with code reviews, but it feels like I've been carrying most of the actual implementation load over the last few months, and so if I don't have the time or inclination to do something, that thing doesn't usually happen until I get around to it.

This is *not* a complaint, and I don't mind - but I don't have unlimited time, and I don't get paid to work on this project, so things are proceeding slower than they otherwise might.

**Comment by bighappyface** [comment]
@erayd understood on both points. You have definitely stepped up, and I agree that more contributions would be helpful.

Unfortunately, I can not set the default branch without admin privileges.

I will set some time aside to get back up to speed and see what I can tackle for `6.0.0`.

**Comment by dkarlovi** [comment]
Can't you guys just fork the project and deprecate the old one in composer.json, like https://github.com/ramsey/uuid did [from rhumsaa/uuid](https://github.com/ramsey/uuid/blob/master/composer.json#L60)?

**Comment by bighappyface** [comment]
@dkarlovi it has been discussed, but the `replace` property hasn't been brought forward before.

Thanks for the tip.

**Comment by erayd** [comment]
@bighappyface Can we merge this into master please, then delete this branch? We aren't actually using master for anything at the moment, and people keep opening pull requests against it because it's the default branch (which we can't change). All further 6.0.0 development would then take place against the matter branch.

If you're OK with this, please do *not* use a merge style that squashes the changes into a single commit! For this one, we want to preserve the full commit history.

**Comment by erayd** [comment]
@bighappyface?

**Comment by erayd** [comment]
@bighappyface Thanks! :-)

**Pull request merged**
