### PR TITLE
marc-mabe/php-enum versions

### PR DESCRIPTION
**Pull request by marc-mabe**
I'm very happy you are planning to use my small library :)

As you are using base functionality only you can support much more versions of it. This helps a lot in cases you have to deal with more libraries and all have different dependent versions.

### CODE REVIEW

**Comment by wimleers** [comment]
Is the intent to make `json-schema` work with both the `2.x` and `3.x` branches of https://github.com/marc-mabe/php-enum?

**Comment by wimleers** [comment]
(Asking this because it's related to #569.)

**Comment by shmax** [comment]
@wimleers  Looks like we sort of forgot to follow up on this one. We only use the most basic, vanilla features of php-enum. I had a quick look at the "BC break" tags listed in the 3.0 release, and I didn't see anything that would impact us. On the other hand, with 3.0 he raises the minimal required version PHP version to 5.6, and we're still on 5.3. So, we can't fully switch to 3.0 without creating PHP dependency issues, and if we stay on 2.0 then we don't always get the latest and greatest. Any suggestions?

**Comment by marc-mabe** [comment]
PR is rebased now

> Is the intent to make json-schema work with both the 2.x and 3.x branches of https://github.com/marc-mabe/php-enum?

yes

**Comment by marc-mabe** [comment]
any update on this ?

**Comment by shmax** [comment]
@erayd I'm not really familiar with the version branch strategy. Which one do we target with this?

**Comment by marc-mabe** [comment]
@shmax `"^2.0 || ^3.0"` is the same as `(>= 2.0.0 && < 3.0.0) || (>= 3.0.0 && < 3.0.0)` in this case the same as simplified `>= 2.0.0 && < 4.0.0`.
Normally (if not configured otherwise) composer will take the latest possible version matching this condition and conditions of other depending projects using this same dependency.

**Comment by erayd** [comment]
> Which one do we target with this?

@shmax - exactly what @marc-mabe said above. That constraint should be fine for what we are doing, so long as you're happy that the syntax is the same for the bits you use - I'm assuming that because you approved the PR, that is the case.

**Comment by shmax** [comment]
I was talking more about master vs one of our version branches (eg. 5.x.x, 6.0.dev). Master it is, then.

**Comment by erayd** [comment]
@shmax Always master. Merging PRs directly into 5.x.x causes problems. This one will probably make it into my next backport release though.

**Pull request merged**
