### PR TITLE
Fix coding style via PHP-CS-Fixer

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log
- Fixing coding style via `php-cs-fixer`.

### CODE REVIEW

**Comment by erayd** [comment]
This PR just runs php-cs-fixer, but does not fix the problem with php-cs-fixer and removes wanted content as a result.

Php-cs-fixer has a track record of making undesirable changes without warning when updated - that needs to be fixed first. Most of the existing codebase should be compliant with the desired behavior.

If you would like to re-style things I'm happy to consider that, but it's really important that we don't lose data / change execution logic as a result, both of which php-cs-fixer has tried to do to this project in the past. We also need a good reason for the style change.

**Comment by erayd** [comment]
See #599 and #600 - perhaps you guys could collaborate on those?

**Comment by peter279k** [comment]
@localheinz, do you have any idea about this :)?

**Comment by localheinz** [comment]
@peter279k 

Thanks for reaching out - I believe we should sort out #600 first, and then see about enabling or configuring rules as we see fit, ideally one by one (unless we feel brave and want to enable and configure a bunch of them at once).

**Comment by peter279k** [comment]
> @peter279k
> 
> Thanks for reaching out - I believe we should sort out #600 first, and then see about enabling or configuring rules as we see fit, ideally one by one (unless we feel brave and want to enable and configure a bunch of them at once).

Hi @localheinz, I agree with you and we can focus on #600 firstly and configuring rules on next steps.

**Pull request closed without merging**
