### PR TITLE
Do not throw errors when using unknown/custom format

### PR DESCRIPTION
**Pull request by lwiesel**

### CODE REVIEW

**Comment by bighappyface** [comment]
@lwiesel would you please rebase and resolve conflicts? Also, would you mind reviewing #134 to see how this update could factor in?

**Comment by Maks3w** [comment]
For the record I attach the specification fragment about this:

> The value of this keyword is called a format attribute. It MUST be a string. A format attribute can generally only validate a given set of instance types. **If the type of the instance to validate is not in this set, validation for this format attribute and instance SHOULD succeed.**

**Comment by Maks3w** [comment]
@bighappyface The PR is rebased. Travis-CI error status is due failure with composer install

**Comment by Maks3w** [comment]
@bighappyface #134 (now #141) should be rebased again when this is merged or you could resolve the conflict

**Comment by onlinesid** [comment]
I screwed up my PR so I've closed and re-created it as #142 

I've removed unknown format error, updated the tests and squashed my commits into one

**Comment by lwiesel** [comment]
Ok, since github is fine again these days, the Travis-CI build passed after my rebase.

These modifications are indeed included in PR #142, but I'd recommend to merge this PR before and keep #142 focused on optional extra argument to keep atomicity in commits. Anyway it's your call!

**Comment by bighappyface** [comment]
+1

**Pull request merged**
