### PR TITLE
Bump json-schema/JSON-Schema-Test-Suite to 1.1.2

### PR DESCRIPTION
**Pull request by mirfilip**
/cc @bighappyface 

No effort move, all tests still passing. I'm currently looking at using `1.2.0` (seen [that](https://github.com/bighappyface/json-schema/pull/1))

### CODE REVIEW

**Comment by bighappyface** [comment]
@mirfilip please use a [global ignore](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore) for the `.idea` directory. That is a user-specific ignore as not everyone uses the Jetbrains products.

Otherwise +1

**Comment by mirfilip** [comment]
@bighappyface I cannot use a global ignore as some projects I work with do keep this under version control. Anyway, it was rather a thing for every other contributor that uses Jetbrains stuff so that the IDE config doesn't get committed.

I've checked some popular repos and they indeed refrain from specifying IDE specific stuff. Reverting that then.

**Comment by bighappyface** [comment]
@mirfilip thanks for the update. Last request: please squash this down.

**Comment by mirfilip** [comment]
@bighappyface Sure! Also, please see #265 as it supersedes this PR.

**Pull request merged**
