### PR TITLE
Backports for 5.2.0

### PR DESCRIPTION
**Pull request by erayd**
Various stuff from [6.0.0](https://github.com/justinrainbow/json-schema/tree/6.0.0-dev) that can be backported to 5.2.0 without breaking backwards-compatibility. Will add new stuff where possible as it's merged.

## Backported PRs
 * #362  (`package://` URIs and bundle local copy of the spec schemas)
 * #372 (bugfix for issue #371)
 * #378 (bugfix for #376, add provided schema under a dummy URI)
 * #382 (add quiet / verbose options to CLI script)
 * #383 (add `CHECK_MODE_DISABLE_FORMAT`)
 * #366 (more unit tests)
 * #389 (allow assoc array as schema)
 * #398 (enable `FILTER_FLAG_EMAIL_UNICODE` if available)
 * #394 (`anyOf` / `oneOf` exceptions - bugfix for #393)
 * #365 (default recursion & bugfixes for #359 & #377, refactor defaults, other minor fixes)
 * #357 (schema validation)
 * #400 (remove stale files from #357)

## Skipped PRs
 * #364 (Centralise errors) - non-backwards-compatible signature changes
 * #370 (Bugfix #369) - not applicable, depends on #364
 * #373 (revert 73ef463 to remove `email` type) - will break for people who rely on this
 * #386 (reset error status before validation) - some people might be doing multiple-validation this way
 * #375 (enum wrapper) - not applicable, depends on #364
 * #384 (coercion improvements) - changes coercion behavior & additional type support

### CODE REVIEW

**Comment by bighappyface** [comment]
Any more items to add here?

5.3.0?

**Comment by erayd** [comment]
@bighappyface You're welcome to merge backport PRs whenever suits - I'll just open another one with a higher version number each time you do. And if you want me to stop adding things to a particular backport PR, just let me know. That way you can decide when you want backport releases to happen, and what you want in them :-).

Looks like I'll have a bit of backporting work to do this weekend though, you've merged a ton of stuff to 6.0.0! :+1:

**Comment by erayd** [comment]
Also thanks for all the merging :-).

**Comment by bighappyface** [comment]
Thanks for your patience and continued work. I know I go silent for weeks at a time, but I am still here.

@erayd @shmax @mathroc you are all [steely-eyed missile men](https://en.wiktionary.org/wiki/steely-eyed_missile_man) 🚀

**Comment by erayd** [comment]
This PR is now up-to-date with what has been merged to [6.0.0-dev](https://github.com/justinrainbow/json-schema/tree/6.0.0-dev).

**Comment by erayd** [comment]
@bighappyface I notice you've added this to merged / closed for [5.2.0](https://github.com/justinrainbow/json-schema/projects/1#card-2113114), but it's not merged or closed. Were you intending this to go in one of the other sections, or are you intending to merge this now?

**Comment by bighappyface** [comment]
@erayd @shmax the various PRs for 6.0.0 are either merged or pending merge after being rebased.

Once they are merged I would like to provide time for backport to 5.x in the master branch, then I will rebase, then we can look at merging 6.0.0.

Does that sound okay?

**Comment by erayd** [comment]
Works for me :-)

**Comment by erayd** [comment]
Although I do think we need to work on #392 before there is an actual tagged 6.0.0 release.

**Comment by bighappyface** [comment]
Anything else going in this? I am ready to go on this so that we can focus on 6.0.0 moving forward.

**Comment by erayd** [comment]
I'm going through the stuff you just merged - I think at least the recursion fix needs to be in this.

**Comment by erayd** [comment]
OK, I think that's everything :-).

**Comment by erayd** [comment]
Have updated the PR description with everything that's in this, and everything that's been skipped.

**Pull request merged**
