### PR TITLE
Bugfix for #215

### PR DESCRIPTION
**Pull request by rtucek**
Fixed bug, discovered in #215. 
Also added regression test.

### CODE REVIEW

**Comment by bighappyface** [comment]
@rtucek thanks for the contribution!

A couple of things:

# Would you please squash this PR down to a single commit?
# Would you please simplify the test schema and document to focus only on demonstrating the code change? Please review the other test cases for this constraint and/or tests in the official test suite (https://github.com/json-schema/JSON-Schema-Test-Suite)

**Comment by rtucek** [comment]
Hi @bighappyface,

thank your for your quick reply.

1) Yeah, that should have been done in the first place - sry.
2) Well, I personally don't agree with simplifying the test. It was a complex schema and JSON that uncovered the bug...

Anyhow, I did the rebase as requested and it passed the test.

**Comment by bighappyface** [comment]
@rtucek thanks for the update.

Upon deeper review of the changes, I think we have misplaced the `minProperties/maxProperties` validation logic in `UndefinedConstraint` when it should be within `ObjectConstraint` as those are validation keywords of objects (http://json-schema.org/latest/json-schema-validation.html#anchor53).

If the validation were located in the appropriate place then the negation added in this PR would probably be unnecessary. Further, this package already validates all of the `minProperties/maxProperties` testcases provided by the JSON Schema Test Suite:

https://github.com/json-schema/JSON-Schema-Test-Suite/blob/1.1.0/tests/draft4/minProperties.json
https://github.com/json-schema/JSON-Schema-Test-Suite/blob/1.1.0/tests/draft4/maxProperties.json

Those test cases demonstrate the constraint validation specifically. That is what I meant by " please simplify the test schema and document to focus only on demonstrating the code change." The latest update to the new test case seems a bit odd to me because it's redundant and the "document" is an empty object literal (`{}`) that doesn't demonstrate the schema provided afterward.

Would you please look at migrating the `minProperties/maxProperties` validation logic to the `ObjectConstraint` class to see if it works are expected with your original schema and JSON document?

**Comment by rtucek** [comment]
Yeah, it would definitely a true fix for the issue - rather than just a dirty one-line quicky :smile: 
Probably I get this done until the end of the week.

**Pull request closed without merging**
